/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mensch.aerger.dich.nicht.view;

import java.awt.Color;
import java.awt.Dimension;
import mensch.aerger.dich.nicht.MenschAergerDichNicht;
import mensch.aerger.dich.nicht.modell.Spielfelder.VierSpielerFeld;
import mensch.aerger.dich.nicht.view.Grafikmanager;
import mensch.aerger.dich.nicht.view.LinesComponent;

/**
 *
 * @author Administrator
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    private LinesComponent comp;
    private Grafikmanager grafikManager;
    private int scale = 50;

    public MainGUI() {
        initComponents();

        comp = new LinesComponent();
        comp.setPreferredSize(new Dimension(1920, 1080));
         getContentPane().setBounds(0, 0, -1, -1);
      //  comp.addMouseListener(this);

        getContentPane().add(comp,  new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
// new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1)
        getContentPane().setBackground(Color.WHITE);

        this.setSize(new Dimension(1024, 785));
        grafikManager = new Grafikmanager(comp);
        setExtendedState(MAXIMIZED_BOTH);

    }
    private VierSpielerFeld spielFeld;

    public void starte() {
        //Wuerfel w = new Wuerfel(6,6);
        //w.werfe();
        spielFeld = new VierSpielerFeld();
    }
    
    public void setzeText(String text){
       // this.jLabel1.setText(text);
    }

    public VierSpielerFeld getSpielFeld() {
        return spielFeld;
    }

    public Grafikmanager getGrafikmanager() {
        return grafikManager;
    }

    public int getScale() {
        return scale;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mensch ärgere Dich nicht");
        setBackground(new java.awt.Color(255, 0, 0));
        setForeground(java.awt.Color.white);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(MenschAergerDichNicht.getSpielSteuerung()!= null){
            MenschAergerDichNicht.getSpielSteuerung().mausClick(evt);
        }
    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
