/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mensch.aerger.dich.nicht;

import java.awt.Color;
import java.awt.Dimension;
import mensch.aerger.dich.nicht.grafik.Grafikmanager;
import mensch.aerger.dich.nicht.grafik.LinesComponent;
import mensch.aerger.dich.nicht.objekts.Spielfelder.VierSpielerFeld;
import mensch.aerger.dich.nicht.objekts.Wuerfel;


/**
 *
 * @author Administrator
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    private LinesComponent comp;
    private Grafikmanager grafikManager;
    private int scale = 50;
    
    public MainGUI() {
        initComponents();
       
        comp = new LinesComponent();
        comp.setPreferredSize(new Dimension(1920, 1080));
      //  comp.addMouseListener(this);
       
        getContentPane().add(comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        
        getContentPane().setBackground(Color.WHITE);
        
        this.setSize(new Dimension(1024, 785));
        grafikManager = new Grafikmanager(comp);
        setExtendedState(MAXIMIZED_BOTH);
       
    }
     private VierSpielerFeld sf;
    public void starte(){
        //Wuerfel w = new Wuerfel(6,6);
        //w.werfe();
        sf = new VierSpielerFeld();
    }
    public Grafikmanager getGrafikmanager() {
        return grafikManager;
    }

    public int getScale() {
        return scale;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Würfeln");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.sf.getW1().werfe();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
